export default {
  response_code: 0,
  results: [
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "What was the original name of the search engine &quot;Google&quot;?",
      correct_answer: "BackRub",
      incorrect_answers: ["CatMassage", "SearchPro", "Netscape Navigator"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What direction does the Statue of Liberty face?",
      correct_answer: "Southeast",
      incorrect_answers: ["Southwest", "Northwest", "Northeast"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "The website &quot;Shut Up &amp; Sit Down&quot; reviews which form of media?",
      correct_answer: "Board Games",
      incorrect_answers: ["Television Shows", "Video Games", "Films"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What was the destination of the missing flight MH370?",
      correct_answer: "Beijing",
      incorrect_answers: ["Kuala Lumpur", "Singapore", "Tokyo"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What does the &quot;G&quot; mean in &quot;G-Man&quot;?",
      correct_answer: "Government",
      incorrect_answers: ["Going", "Ghost", "Geronimo"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "The architect known as Le Corbusier was an important figure in what style of architecture?",
      correct_answer: "Modernism",
      incorrect_answers: ["Neoclassical", "Baroque", "Gothic Revival"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the Italian word for &quot;tomato&quot;?",
      correct_answer: "Pomodoro",
      incorrect_answers: ["Aglio", "Cipolla", "Peperoncino"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the average life span of a garden ant?",
      correct_answer: "15 years",
      incorrect_answers: ["24 hours", "1 week", "3 years"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Who invented Pastafarianism?",
      correct_answer: "Bobby Henderson",
      incorrect_answers: ["Eric Tignor", "Bill Nye", "Zach Soldi"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "In the Morse code, which letter is indicated by 3 dots? ",
      correct_answer: "S",
      incorrect_answers: ["O", "A", "C"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What year was Apple Inc. founded?",
      correct_answer: "1976",
      incorrect_answers: ["1978", "1980", "1974"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "A doctor with a PhD is a doctor of what?",
      correct_answer: "Philosophy",
      incorrect_answers: ["Psychology", "Phrenology", "Physical Therapy"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Which of these words means &quot;idle spectator&quot;?",
      correct_answer: "Gongoozler",
      incorrect_answers: ["Gossypiboma", "Jentacular", "Meupareunia"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the romanized Russian word for &quot;winter&quot;?",
      correct_answer: "Zima",
      incorrect_answers: ["Leto", "Vesna", "Osen&#039;"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Which of these companies does NOT manufacture automobiles?",
      correct_answer: "Ducati",
      incorrect_answers: ["Nissan", "GMC", "Fiat"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "What name represents the letter &quot;M&quot; in the NATO phonetic alphabet?",
      correct_answer: "Mike",
      incorrect_answers: ["Matthew", "Mark", "Max"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the star sign of someone born on Valentines day?",
      correct_answer: "Aquarius",
      incorrect_answers: ["Pisces", "Capricorn", "Scorpio"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "Frank Lloyd Wright was the architect behind what famous building?",
      correct_answer: "The Guggenheim",
      incorrect_answers: [
        "Villa Savoye",
        "Sydney Opera House",
        "The Space Needle",
      ],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "A statue of Charles Darwin sits in what London museum?",
      correct_answer: "Natural History Museum",
      incorrect_answers: ["Tate", "British Museum", "Science Museum"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What does a milliner make and sell?",
      correct_answer: "Hats",
      incorrect_answers: ["Shoes", "Belts", "Shirts"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "After how many years would you celebrate your crystal anniversary?",
      correct_answer: "15",
      incorrect_answers: ["20", "10", "25"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "In ancient Greece, if your job were a &quot;hippeus&quot; which of these would you own?",
      correct_answer: "Horse",
      incorrect_answers: ["Weave", "Guitar", "Boat"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "This field is sometimes known as &ldquo;The Dismal Science.&rdquo;",
      correct_answer: "Economics",
      incorrect_answers: ["Philosophy", "Politics", "Physics"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the last letter of the Greek alphabet?",
      correct_answer: "Omega",
      incorrect_answers: ["Mu", "Epsilon", "Kappa"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Rolex is a company that specializes in what type of product?",
      correct_answer: "Watches",
      incorrect_answers: ["Cars", "Computers", "Sports equipment"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Which country drives on the left side of the road?",
      correct_answer: "Japan",
      incorrect_answers: ["Germany", "Russia", "China"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Amsterdam Centraal station is twinned with what station?",
      correct_answer: "London Liverpool Street",
      incorrect_answers: [
        "Frankfurt (Main) Hauptbahnhof",
        "Paris Gare du Nord",
        "Brussels Midi",
      ],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "What is the world&#039;s most expensive spice by weight?",
      correct_answer: "Saffron",
      incorrect_answers: ["Cinnamon", "Cardamom", "Vanilla"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question: "Earl Grey tea is black tea flavoured with what?",
      correct_answer: "Bergamot oil",
      incorrect_answers: ["Lavender", "Vanilla", "Honey"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "General Knowledge",
      question:
        "Which iconic Disneyland attraction was closed in 2017 to be remodeled as a &quot;Guardians of the Galaxy&quot; themed ride?",
      correct_answer: "Twilight Zone Tower of Terror",
      incorrect_answers: [
        "The Haunted Mansion",
        "Pirates of the Caribbean",
        "Peter Pan&#039;s Flight",
      ],
    },
  ],
};
